events {}

http {
    charset utf-8;

    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

    server {
        listen 80;
        server_name project1.local project2.local;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name project1.local;

        location / {
            root /usr/share/nginx/html/project1;
            index index.html;
        }
    }

    server {
        listen 443 ssl;
        server_name project2.local;

        location / {
            root /usr/share/nginx/html/project2;
            index index.html;
        }

        location /assets/ {
            alias /usr/share/nginx/html/project2/static/;
        }
    }
}
